# Local Search Implementation on Diagonal Magic Cube
## Made by:
- Jeremy Deandito / 18222112 

- Nathaniel Liady / 18222114

- Gabriel Marcellino / 18222115

- Nicolas Jeremy / 18222135

## Import relevant libraries

In [1]:
from tensor import *

from simulated import *


import numpy as np

## Cube Initialization

### Goal State
 Final state cube we are trying to achieve.<br><br> 
 The ideal state

In [2]:
goal_state = [

# Level 1
[
    [33, 22, 113, 42, 105],
    [2, 89, 106, 19, 99],
    [85, 82, 4, 119, 25],
    [98, 90, 6, 112, 9],
    [97, 32, 86, 23, 77]
],
# Level 2
[
    [95, 80, 111, 11, 18],
    [91, 55, 65, 69, 35],
    [16, 66, 70, 53, 110],
    [5, 68, 54, 67, 121],
    [108, 46, 15, 115, 31]
],
# Level 3
[
    [100, 17, 48, 34, 116],
    [114, 75, 52, 62, 12],
    [83, 50, 63, 76, 43],
    [8, 64, 74, 51, 118],
    [10, 109, 78, 92, 26]
],
# Level 4
[
    [38, 102, 3, 125, 47],
    [81, 59, 72, 58, 45],
    [30, 73, 56, 60, 96],
    [87, 57, 61, 71, 39],
    [79, 24, 123, 1, 88]
],
# Level 5
[
    [49, 94, 40, 103, 29],
    [27, 37, 20, 107, 124],
    [101, 44, 122, 7, 41],
    [117, 36, 120, 14, 28],
    [21, 104, 13, 84, 93]
]
]

In [3]:
goal_cube = Tensor(5,5,5,initial_array=goal_state)

### Problem Cube Initialization

In [4]:
problem_cube = Tensor(5,5,5)

cube = problem_cube.initial_state()

In [5]:
# cube.plot_cube()

In [6]:
# cube.plot_per_level()

In [7]:
obj_func = cube.objective_function()
print(f"cube's objective function: {obj_func}")

cube's objective function: 1646347.0


## Local Seach Implementation

### Steepest Ascent Hill-Climbing

### Simulated Annealing

In [8]:
cube.print_tensor()

Level: 1

[118 124  34  65   8]
[ 15 112 104  62  10]
[  5  39  28  70 107]
[120  61  22   7  12]
[  6  49  31  79 100]

Level: 2

[122  98   9  58 123]
[117  16  54  86  46]
[67 81 36 18 13]
[ 68 116 101  91   4]
[71 77 72 60 88]

Level: 3

[ 51  73 119  85 106]
[103  63  45  32   3]
[ 74 111  64  17   1]
[44 26 25 94 48]
[ 42  43  87 102  83]

Level: 4

[35 37 38 97 93]
[110  75  24 125  69]
[ 55  30  89  96 114]
[76 80 92 57 82]
[ 78  95 105  47  20]

Level: 5

[23  2 14 84 50]
[115 121  52  66  11]
[ 40  56  19 113 108]
[ 90  59  27  41 109]
[33 29 53 99 21]



In [9]:
SA = Simulated(cube=cube,tmax=1000,step_max=10000)

Initial Energy: 1646347.0

best_energy = 1646347.0

current_energy = 1646347.0

e_n = 1645051.0

de = -1296.0

best_energy = 1645051.0

current_energy = 1645051.0

de = 395.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 18480.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 32400.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 30736.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 29136.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 69138.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 71798.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 93938.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 70124.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 57496.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 46796.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 95026.0

best_energy = 1645051.0

current_energy = 1645446.0

de = 102982.0

best_energy = 16450

In [10]:
SA.results()

+------------------------ RESULTS -------------------------+

cooling sched.: linear additive
  initial temp: 1000
    final temp: 0.000000
     max steps: 10000
    final step: 10001

  final energy: 1427218.000000

+-------------------------- END ---------------------------+


### Genetic Algorithm
