# Local Search Implementation on Diagonal Magic Cube
## Made by:
- Jeremy Deandito / 18222112 

- Nathaniel Liady / 18222114

- Gabriel Marcellino / 18222115

- Nicolas Jeremy / 18222135

## Import relevant libraries

In [1]:
from tensor import *

from simulated import *


import numpy as np

## Cube Initialization

### Goal State
 Final state cube we are trying to achieve.<br><br> 
 The ideal state

In [2]:
goal_state = [

# Level 1
[
    [33, 22, 113, 42, 105],
    [2, 89, 106, 19, 99],
    [85, 82, 4, 119, 25],
    [98, 90, 6, 112, 9],
    [97, 32, 86, 23, 77]
],
# Level 2
[
    [95, 80, 111, 11, 18],
    [91, 55, 65, 69, 35],
    [16, 66, 70, 53, 110],
    [5, 68, 54, 67, 121],
    [108, 46, 15, 115, 31]
],
# Level 3
[
    [100, 17, 48, 34, 116],
    [114, 75, 52, 62, 12],
    [83, 50, 63, 76, 43],
    [8, 64, 74, 51, 118],
    [10, 109, 78, 92, 26]
],
# Level 4
[
    [38, 102, 3, 125, 47],
    [81, 59, 72, 58, 45],
    [30, 73, 56, 60, 96],
    [87, 57, 61, 71, 39],
    [79, 24, 123, 1, 88]
],
# Level 5
[
    [49, 94, 40, 103, 29],
    [27, 37, 20, 107, 124],
    [101, 44, 122, 7, 41],
    [117, 36, 120, 14, 28],
    [21, 104, 13, 84, 93]
]
]

In [3]:
goal_cube = Tensor(5,5,5,initial_array=goal_state)

### Problem Cube Initialization

In [4]:
problem_cube = Tensor(5,5,5)

cube = problem_cube.initial_state()

In [5]:
# cube.plot_cube()

In [6]:
# cube.plot_per_level()

In [7]:
obj_func = cube.objective_function()
print(f"cube's objective function: {obj_func}")

cube's objective function: 1734358.0


## Local Seach Implementation

### Steepest Ascent Hill-Climbing

### Simulated Annealing

In [8]:
cube.print_tensor()

Level: 1

[65 19 14 60 24]
[ 78  64 112  77 125]
[47 71 61 51 10]
[ 36  33  74  35 107]
[117  70  42 123   8]

Level: 2

[57 38 88 84 63]
[ 82  21  62 120 119]
[ 16 110  92  28  81]
[13 79 87 31 98]
[ 58  17 122   9  11]

Level: 3

[ 56  49  34  55 114]
[80 46 75 41 39]
[91 95 59  6 43]
[90 50 66  4 93]
[109  45 116  54   5]

Level: 4

[18 53 68  3 48]
[40 94 22 32 97]
[72 20 89 73 25]
[ 99  37  26 101  12]
[115  44  83   7 102]

Level: 5

[121   2  67  23 106]
[111 124  86  27 108]
[ 96 103 105  85  30]
[  1  52 100  15  76]
[ 29  69 118 104 113]



In [9]:
SA = Simulated(cube=cube,tmax=2000,step_max=10000,cooling_schedule="quadratic",alpha=0.99)

Initial Energy: 1734358.0

best_energy = 1734358.0

current_energy = 1734358.0

de = 1542.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 26288.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 21388.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 51200.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 52168.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 52264.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 17924.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 44944.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 58731.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 51780.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 24876.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 29092.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 25420.0

best_energy = 1734358.0

current_energy = 1735900.0

de = 37894.0

best_energy = 1734358.0

current_ene

In [10]:
SA.final_state()

Level: 1

[  5 119  53   2  98]
[ 18  29  28 123  78]
[90 82 54  1 42]
[90 21 80 62 72]
[123  28  11  18 100]

Level: 2

[104   0  57  54  79]
[ 70 118  24  78  80]
[ 7 58 19 20 44]
[ 48  44  66 118   0]
[  6   0 115 120  48]

Level: 3

[ 14  96 118 122   0]
[ 43  74 110   0  44]
[ 21 112   7  33  37]
[ 71  13 124  92 103]
[100  95  95  17   8]

Level: 4

[84 68 33 92  6]
[ 31  41 120  70   7]
[112  29  80  37   0]
[  3  84 121  30 120]
[115   0 106   5 119]

Level: 5

[ 99  38 118 110   0]
[ 41  36  31  21 116]
[75 91 14 36  2]
[54 32  6 96 88]
[82  8 13 38 54]



In [12]:
SA.results()

+------------------------ RESULTS -------------------------+

cooling sched.: quadratic multiplicative
  initial temp: 2000
    final temp: 0.000000
     max steps: 10000
    final step: 10001

  final energy: 1416179.000000

+-------------------------- END ---------------------------+


### Genetic Algorithm
